# Generated by Django 5.1.1 on 2024-09-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('insight', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=4, null=True)),
                ('end_year', models.CharField(blank=True, max_length=4, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('likelihood', models.IntegerField()),
                ('intensity', models.IntegerField()),
            ],
        ),
    ]
