# Generated by Django 5.1.1 on 2024-09-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energyinsight',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
