# Generated by Django 5.1.2 on 2024-10-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_remove_products_orders_alter_products_p_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='orders',
            field=models.ManyToManyField(to='zomato.orders'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
