# Generated by Django 5.1.2 on 2024-10-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0003_products_orders_alter_products_p_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='orders',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='zomato.products'),
        ),
    ]
